### ISSUE TITLE
Not working sites

### ISSUE THREAD

**Issue by circcc** [lunu-bounir/allow-right-click.html#14]
These korean sites are not working
- https://mama-iamhere.tistory.com/entry/%ED%8B%B0%EC%8A%A4%ED%86%A0%EB%A6%AC-%EB%82%B4-%EA%B8%80-%EB%B3%B5%EC%82%AC-%EB%B0%A9%EC%A7%80-%EB%B0%8F-%EB%93%9C%EB%9E%98%EA%B7%B8-%EA%B8%88%EC%A7%80-%EB%B0%A9%EB%B2%95
- https://m.blog.naver.com/PostView.nhn?blogId=falling_y&logNo=220740048425&proxyReferer=https:%2F%2Fwww.google.com%2F
- https://blog.daum.net/simhsook48/2592

Happy Right-Click(https://addons.mozilla.org/en-US/firefox/addon/%E5%BF%AB%E4%B9%90%E5%8F%B3%E9%94%AE/) and Drag-Free(https://addons.mozilla.org/en-US/firefox/addon/%EB%93%9C%EB%9E%98%EA%B7%B8-%ED%94%84%EB%A6%AC/) are working for these sites.

**Comment by lunu-bounir** [comment]
Thanks for the report. It is fixed on 0.3.0 release
