### ISSUE TITLE
It's break right click in Win10 at all

### ISSUE THREAD

**Issue by zidercol** [lunu-bounir/allow-right-click.html#15]
I lost possibility to right click application in taskbar even after delete application. 
Win10 20H2

**Comment by lunu-bounir** [comment]
This bug is not related to this extension for two reasons:

1. When you delete an extension it cannot have any impact on any page anymore.
2. This extension only can alter things inside web pages, not Windows itself.

Try to look for a native application. No extension can be responsible.

**Comment by zidercol** [comment]
Are you sure ? I found that right click disfunction after 10 seconds after install. At first step I get full right click disfunction. After deletion I have only taskbar rightclick disfunction. If I press Shift I can right click any app in taskbar Except browsers.

**Comment by lunu-bounir** [comment]
Yes, I am sure. No extension can affect outside browser windows.
