### ISSUE TITLE
Site that new versions are not working again...

### ISSUE THREAD

**Issue by circcc** [lunu-bounir/allow-right-click.html#17]
https://everyhark.tistory.com/298

0.3.3 is working with this site,
but 0.4.0, 0.4.1 is not working.

Please fix it.

**Comment by lunu-bounir** [comment]
I am not able to reproduce the issue on 0.4.1. What is the problem? Are you using FF?

**Comment by circcc** [comment]
Yes, I'm using FF 90.0b12 for windows. I can't text section.

**Comment by lunu-bounir** [comment]
https://user-images.githubusercontent.com/40388903/124427447-ef81fa00-dd5a-11eb-93d9-4117b5e7db99.mp4

I am not sure why users doesn't work. Maybe there is a conflict.

**Comment by circcc** [comment]
I found reason.
Allow Right-Click is conflict with "Dark Background and Light Text (https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/)". I can solve the problem by temporarily disabling the extension.
I'd appreciate it if you could fix it.

**Comment by lunu-bounir** [comment]
Should be fixed by 0.4.2 release

**Comment by circcc** [comment]
Thanks. 
0.4.2 is working.
