### ISSUE TITLE
time to uninstall this useless addon

### ISSUE THREAD

**Issue by andika207** [lunu-bounir/allow-right-click.html#22]
I finally found a website which doesn't allow copying text unless I read it with IE engine (not Webkit)
https://www.motofichas.com/marcas/benelli/leoncino-250
I have already deleted this crap addon because it doesn't work on my chrome based browser.
https://add0n.com/allow-right-click.html

**Comment by 1baiser** [comment]
I really like this addon and use it everyday but theres something wrong with the application since the last 2 days it does not work on mozilla also I hope they fix it soon.

**Comment by lunu-bounir** [comment]
@1baiser I just checked, and it works fine for me. Can you provide an example page with the issue? Also, you can try the extension on a clean profile to confirm that it is not a conflict with another extension.

**Comment by 1baiser** [comment]
Hello, downloading the last previous version can fix this problem. There's
no specific page. I mean it does not work for all the pages but like i said
i am using the previous version and everything seems fine.

Lunu Bounir ***@***.***>, 2 Oca 2022 Paz, 13:54 tarihinde
şunu yazdı:

**Comment by andika207** [comment]
freedom of speech ?
you closed this issue instead of working this out. LOL

**Comment by lunu-bounir** [comment]
@andika207 The issue is closed with a commit which means that it is fixed.

**Comment by lunu-bounir** [comment]
@1baiser Since I am adding new methods to the latest release, we need to find out what has gone wrong. In case, you can provide steps to reproduce, please open a new bug report.
