### ISSUE TITLE
JWPlayer

### ISSUE THREAD

**Issue by onemenzel** [lunu-bounir/allow-right-click.html#3]
The JWPlayer prevents right clicking and press and hold on Firefox for Android for the video element it controls, but "allow right click" cannot prevent it from overriding Firefox' default behavior.

Example Page: http://onepiece-tube.com/folge/847-aP1eTEqs

**Comment by lunu-bounir** [comment]
Thanks for the report. I haven't tried the new release on a mobile device since I could reproduce this on Desktop too. Should have been fixed!
