### ISSUE TITLE
https://nyugatifeny.hu Only Select All and copy works after right clicking

### ISSUE THREAD

**Issue by hopalongrock** [lunu-bounir/allow-right-click.html#8]
Firefox 80.0.1 on Windows 10 x64 2004.

On https://nyugatifeny.hu I can't select text with mouse,
Also caret browsing doesn't work, although Options - Browsing - "Always use the cursor keys to navigate within pages" is Enabled.

Select All and copy works fine.

No problems with other sites.

**Comment by hopalongrock** [comment]
Now version 0.2.2 works fine with manual activate.
I put nyugatifeny.hu into the "automatically activate extension on hostnames list" and saved.
Although on reload the button is colored, the extension isn't activated on the site, and I have to remove the hostname from the list, and manually activate the extension on the site.

**Comment by lunu-bounir** [comment]
Should be fixed by the next release. Thanks for the report.
